"""Build analysis.ipynb — run once to regenerate."""
import nbformat as nbf

nb = nbf.v4.new_notebook()
nb.metadata["kernelspec"] = {"display_name": "Python 3", "language": "python", "name": "python3"}


def md(src):
    return nbf.v4.new_markdown_cell(src)


def code(src):
    return nbf.v4.new_code_cell(src)


cells = []

# ─── TITLE ───────────────────────────────────────────────────────────────────
cells.append(md(
    "# Morpho Risk Case Study\n"
    "## xUSD / deUSD / sdeUSD Depeg — November 2025\n"
    "### Exploratory Analysis & Research Plan\n\n"
    "This notebook translates raw Morpho API data into answers to the five dashboard questions "
    "and the two debrief topics. It is designed as a research skeleton — conclusions here feed "
    "directly into the dashboard narrative.\n\n"
    "| Section | Question answered |\n"
    "|---------|------------------|\n"
    "| **0** | Setup, helpers, data inventory |\n"
    "| **1** | Data quality & coverage checks |\n"
    "| **2** | Q1-2: Which markets/vaults were exposed, and what were the losses? |\n"
    "| **3** | Q3-4: Did curators exit early? What actions did they take? |\n"
    "| **4** | Q5: How did vault liquidity evolve over the period? |\n"
    "| **5** | Debrief: Why did the liquidation mechanism fail? |\n"
    "| **6** | Debrief: Is liquidity risk truly isolated across Morpho markets? |\n\n"
    "> **Data window:** 1 Nov 2025 - 30 Nov 2025 UTC  \n"
    "> **Collateral assets:** xUSD (Stream Finance), deUSD & sdeUSD (Elixir)  \n"
    "> **Primary source:** Morpho GraphQL API (no Dune credits consumed)\n"
))

# ─── 0: SETUP ─────────────────────────────────────────────────────────────────
cells.append(md("## 0 · Setup & data loading"))

cells.append(code(
    "import json, math, warnings\n"
    "from datetime import datetime, timezone\n"
    "from pathlib import Path\n"
    "from collections import Counter\n\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.dates as mdates\n"
    "import matplotlib.patches as mpatches\n"
    "import matplotlib.ticker as mticker\n"
    "import numpy as np\n\n"
    "warnings.filterwarnings('ignore')\n"
    "pd.set_option('display.max_colwidth', 90)\n"
    "pd.set_option('display.float_format', '{:,.2f}'.format)\n\n"
    "C_BLUE   = '#3A7EBF'\n"
    "C_ORANGE = '#E07B39'\n"
    "C_GREEN  = '#4CAF7D'\n"
    "C_RED    = '#C0392B'\n"
    "C_PURPLE = '#7B5EA7'\n"
    "C_GREY   = '#7F8C8D'\n\n"
    "DATA = Path('data')\n"
    "NOV_START = datetime(2025, 11,  1, tzinfo=timezone.utc)\n"
    "NOV_END   = datetime(2025, 11, 30, 23, 59, 59, tzinfo=timezone.utc)\n\n"
    "def load(name):\n"
    "    return json.loads((DATA / name).read_text())\n\n"
    "def ts(unix): return datetime.fromtimestamp(int(unix), tz=timezone.utc)\n"
    "def fmt_m(v): return f'${v/1e6:,.1f}M' if abs(v) >= 1e6 else f'${v:,.0f}'\n\n"
    "def xy_to_df(series, col='value', filter_nov=True):\n"
    "    rows = [{'date': ts(p['x']), col: p['y']} for p in series if p.get('y') is not None]\n"
    "    if not rows:\n"
    "        return pd.DataFrame(columns=['date', col])\n"
    "    df = pd.DataFrame(rows).sort_values('date').reset_index(drop=True)\n"
    "    if filter_nov:\n"
    "        df = df[(df['date'] >= NOV_START) & (df['date'] <= NOV_END)]\n"
    "    return df\n\n"
    "assets      = load('incident_assets.json')\n"
    "markets     = load('markets.json')\n"
    "liq_txs     = load('liquidations.json')\n"
    "liq_summary = load('liquidation_summary.json')\n"
    "hist_mkts   = load('historical_markets.json')\n"
    "hist_vaults = load('historical_vaults.json')\n"
    "prices      = load('collateral_prices.json')\n"
    "positions   = load('market_top_positions.json')\n"
    "activity    = load('market_activity_tx.json')\n"
    "mm_activity = load('metamorpho_activity.json')\n"
    "v2_top      = load('vaults_v2_top.json')\n"
    "v1_incident = load('vaults_v1_incident.json')\n"
    "supply_vaults = load('supplying_vaults.json')\n"
    "errors      = load('etl_extended_errors.json')\n\n"
    "df_mkts = pd.json_normalize(markets)\n"
    "df_mkts['lltv_pct']      = df_mkts['lltv'].astype(float) / 1e18 * 100\n"
    "df_mkts['chain_id']      = df_mkts['loanAsset.chain.id']\n"
    "df_mkts['collateral']    = df_mkts['collateralAsset.symbol']\n"
    "df_mkts['loan']          = df_mkts['loanAsset.symbol']\n"
    "df_mkts['label']         = df_mkts['collateral'] + ' / ' + df_mkts['loan']\n"
    "df_mkts['borrow_usd']    = pd.to_numeric(df_mkts['state.borrowAssetsUsd'],    errors='coerce').fillna(0)\n"
    "df_mkts['supply_usd']    = pd.to_numeric(df_mkts['state.supplyAssetsUsd'],    errors='coerce').fillna(0)\n"
    "df_mkts['liquidity_usd'] = pd.to_numeric(df_mkts['state.liquidityAssetsUsd'], errors='coerce').fillna(0)\n"
    "df_mkts['utilization']   = pd.to_numeric(df_mkts['state.utilization'],         errors='coerce').fillna(0)\n"
    "df_mkts['warn_types']    = df_mkts['warnings'].apply(lambda ws: [w['type'] for w in ws])\n\n"
    "KEY_MARKET_UK = '0x0f9563442d64ab3bd3bcb27058db0b0d4046a4c46f0acd811dacae9551d2b129'\n\n"
    "print(f'Loaded {len(assets)} incident assets | {len(markets)} markets | {len(liq_txs)} liquidation txs')\n"
    "print(f'       {len(hist_mkts)} historical market series | {len(prices)} price series | {len(errors)} ETL errors')\n"
))

# ─── 1: QC ────────────────────────────────────────────────────────────────────
cells.append(md(
    "## 1 · Data quality checks\n\n"
    "Before drawing conclusions, we verify coverage and flag gaps:\n\n"
    "- Are all three incident assets resolved on-chain?\n"
    "- Does the Morpho oracle price history cover November 2025? Are there null gaps (oracle staleness)?\n"
    "- Do historical market timeseries cover the full incident window?\n"
    "- Which markets carry material debt vs zero-activity placeholders?\n"
))

cells.append(code(
    "df_assets = pd.DataFrame([{\n"
    "    'Symbol': a['symbol'], 'Address': a['address'],\n"
    "    'Decimals': a['decimals'], 'Chain': a['chain']['network'],\n"
    "} for a in assets])\n"
    "print('Incident collateral assets confirmed on-chain:')\n"
    "display(df_assets)\n"
))

cells.append(code(
    "exp = df_mkts.copy()\n"
    "exp['warnings_short'] = exp['warn_types'].apply(\n"
    "    lambda ws: ', '.join(w.replace('_',' ') for w in ws))\n"
    "cols = ['label','lltv_pct','borrow_usd','supply_usd','liquidity_usd','utilization','warnings_short']\n"
    "print('All incident-collateral markets (current snapshot):')\n"
    "display(\n"
    "    exp[cols].sort_values('borrow_usd', ascending=False)\n"
    "    .rename(columns={'label':'Market','lltv_pct':'LLTV%','borrow_usd':'Borrow$',\n"
    "                     'supply_usd':'Supply$','liquidity_usd':'Liquidity$',\n"
    "                     'utilization':'Util','warnings_short':'Warnings'})\n"
    "    .reset_index(drop=True)\n"
    ")\n"
))

cells.append(code(
    "# Price coverage heatmap\n"
    "fig, axes = plt.subplots(1, len(prices), figsize=(14, 3), squeeze=False)\n"
    "for i, series in enumerate(prices):\n"
    "    ax = axes[0][i]\n"
    "    pts = series.get('historicalPriceUsd', [])\n"
    "    has_data = [1 if p['y'] is not None else 0 for p in pts]\n"
    "    colors = [C_GREEN if v else C_RED for v in has_data]\n"
    "    ax.bar(range(len(has_data)), [1]*len(has_data), color=colors,\n"
    "           edgecolor='none', width=1)\n"
    "    ax.set_yticks([])\n"
    "    ax.set_xlim(0, 30)\n"
    "    non_null = sum(has_data)\n"
    "    ax.set_title(f\"{series['symbol']}\\n{non_null}/30 days non-null\",\n"
    "                 fontsize=9, fontweight='bold')\n"
    "    ax.set_xlabel('Day in window')\n"
    "patch_ok   = mpatches.Patch(color=C_GREEN, label='Price data')\n"
    "patch_null = mpatches.Patch(color=C_RED,   label='Null / stale oracle')\n"
    "fig.legend(handles=[patch_ok, patch_null], loc='lower center', ncol=2, fontsize=9)\n"
    "fig.suptitle('Oracle price feed coverage — Nov 2025 (each bar = 1 day)',\n"
    "             fontweight='bold')\n"
    "plt.tight_layout(rect=[0, 0.12, 1, 1])\n"
    "plt.show()\n"
    "print('Null/red bars = oracle staleness or depeg so severe the feed returned no value.')\n"
    "print('This is direct evidence of oracle failure during the stress event.')\n"
))

# ─── 2: EXPOSURE ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 2 · Q1-2: Which markets and vaults were exposed, and what were the losses?\n\n"
    "### Research plan\n"
    "We need to map:\n"
    "1. **Exposure** — which Morpho markets listed xUSD / deUSD / sdeUSD as collateral, "
    "and which vaults were supplying to those markets?\n"
    "2. **Losses** — how much borrow remained outstanding, how much was recovered via "
    "liquidations, and how much constitutes irrecoverable bad debt?\n\n"
    "### Key finding (preview)\n"
    "One market dominates completely: **sdeUSD/USDC** with ~**$130M** borrow at "
    "**100% utilization** and **$0 pool liquidity**. Every other market is "
    "sub-$25k. All markets have `no_whitelisted_allocation` warnings — meaning "
    "**no curator-managed vault was supplying to any of these markets**.\n"
))

cells.append(code(
    "# Borrow exposure bar chart\n"
    "active = df_mkts[df_mkts['borrow_usd'] > 0.01].sort_values('borrow_usd', ascending=False).reset_index(drop=True)\n"
    "cmap = {'sdeUSD': C_BLUE, 'deUSD': C_ORANGE, 'xUSD': C_GREEN}\n"
    "bar_cols = [cmap.get(r, C_GREY) for r in active['collateral']]\n\n"
    "fig, ax = plt.subplots(figsize=(11, max(3.5, len(active)*0.75)))\n"
    "bars = ax.barh(active['label'], active['borrow_usd']/1e6,\n"
    "               color=bar_cols, edgecolor='white', height=0.6)\n"
    "for bar, row in zip(bars, active.itertuples()):\n"
    "    label_str = f'  {fmt_m(row.borrow_usd)}  [{row.utilization*100:.0f}% util]'\n"
    "    ax.text(bar.get_width()+0.3, bar.get_y()+bar.get_height()/2,\n"
    "            label_str, va='center', fontsize=9)\n"
    "ax.set_xlabel('Borrow outstanding (USD millions)')\n"
    "ax.set_title('Outstanding Borrow by Market — Incident-Collateral Snapshot',\n"
    "             fontweight='bold')\n"
    "ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x,_: f'${x:.0f}M'))\n"
    "ax.set_xlim(0, active['borrow_usd'].max()/1e6 * 1.4)\n"
    "ax.invert_yaxis()\n"
    "legend_patches = [\n"
    "    mpatches.Patch(color=C_BLUE,   label='sdeUSD collateral'),\n"
    "    mpatches.Patch(color=C_ORANGE, label='deUSD collateral'),\n"
    "    mpatches.Patch(color=C_GREEN,  label='xUSD collateral'),\n"
    "]\n"
    "ax.legend(handles=legend_patches, fontsize=9)\n"
    "ax.grid(axis='x', alpha=0.3)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
))

cells.append(md(
    "### QA: borrow by collateral (why not a pie chart?)\n\n"
    "A **pie chart** with one bucket at ~100% and others at under 0.02% makes every other slice "
    "invisible and **overlaps labels** (e.g. `deUSD` vs `xUSD`). For QA you need **exact USD** "
    "and **percent of total** in a table, plus a **linear bar** for the full picture and a "
    "**log-scale** bar so non-zero small exposures stay auditable.\n"
))

cells.append(code(
    "# Borrow by collateral: table + linear bar + log-scale bar (QA)\n"
    "by_coll = (\n"
    "    df_mkts.groupby('collateral', as_index=False)\n"
    "    .agg(borrow_usd=('borrow_usd', 'sum'), markets=('uniqueKey', 'count'))\n"
    "    .sort_values('borrow_usd', ascending=False)\n"
    "    .reset_index(drop=True)\n"
    ")\n"
    "tot_b = by_coll['borrow_usd'].sum()\n"
    "by_coll['pct_of_total'] = (by_coll['borrow_usd'] / tot_b * 100) if tot_b else 0\n"
    "print('Borrow exposure by collateral — source of truth for QA:')\n"
    "display(by_coll)\n\n"
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 4))\n"
    "cmap3 = {'sdeUSD': C_BLUE, 'deUSD': C_ORANGE, 'xUSD': C_GREEN}\n"
    "bar_c = [cmap3.get(c, C_GREY) for c in by_coll['collateral']]\n"
    "ax1.barh(by_coll['collateral'], by_coll['borrow_usd'] / 1e6, color=bar_c, edgecolor='white')\n"
    "for i, (_, r) in enumerate(by_coll.iterrows()):\n"
    "    ax1.text(r['borrow_usd']/1e6 + max(by_coll['borrow_usd'])/1e6*0.01, i,\n"
    "             f\"{fmt_m(r['borrow_usd'])}  ({r['pct_of_total']:.4f}%)\", va='center', fontsize=9)\n"
    "ax1.set_xlabel('Borrow (USD millions)')\n"
    "ax1.set_title('Linear scale — dominance visible', fontweight='bold')\n"
    "ax1.invert_yaxis()\n"
    "ax1.grid(axis='x', alpha=0.3)\n\n"
    "pos = by_coll[by_coll['borrow_usd'] > 0].copy()\n"
    "ax2.barh(pos['collateral'], pos['borrow_usd'], color=[cmap3.get(c, C_GREY) for c in pos['collateral']],\n"
    "         edgecolor='white')\n"
    "ax2.set_xscale('log')\n"
    "ax2.set_xlabel('Borrow (USD, log scale)')\n"
    "ax2.set_title('Log scale — non-zero tail is readable', fontweight='bold')\n"
    "ax2.invert_yaxis()\n"
    "ax2.grid(axis='x', alpha=0.3)\n"
    "for i, (_, r) in enumerate(pos.iterrows()):\n"
    "    ax2.text(r['borrow_usd'] * 1.15, i, f\"${r['borrow_usd']:,.2f}\", va='center', fontsize=9)\n\n"
    "plt.suptitle('Borrow exposure by collateral (current snapshot) — QA view', fontweight='bold', y=1.02)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
))

cells.append(code(
    "# LLTV vs Utilization scatter\n"
    "cmap2 = {'sdeUSD': C_BLUE, 'deUSD': C_ORANGE, 'xUSD': C_GREEN}\n"
    "pt_cols = [cmap2.get(r, C_GREY) for r in df_mkts['collateral']]\n"
    "sizes   = (df_mkts['borrow_usd'].clip(lower=0.01)+1).apply(math.log) * 80\n\n"
    "fig, ax = plt.subplots(figsize=(9, 6))\n"
    "ax.scatter(df_mkts['lltv_pct'], df_mkts['utilization']*100,\n"
    "           s=sizes, c=pt_cols, alpha=0.75, edgecolors='white', linewidths=0.7)\n"
    "for _, row in df_mkts[df_mkts.borrow_usd > 100].iterrows():\n"
    "    ax.annotate(f\"{row['label']}\\n{fmt_m(row['borrow_usd'])}\",\n"
    "                (row['lltv_pct'], row['utilization']*100),\n"
    "                xytext=(10, -18), textcoords='offset points', fontsize=8,\n"
    "                arrowprops=dict(arrowstyle='-', color='gray', lw=0.7))\n"
    "ax.axhline(100, color=C_RED, linestyle='--', linewidth=1, label='100% utilization')\n"
    "ax.set_xlabel('LLTV (%)')\n"
    "ax.set_ylabel('Utilization (%)')\n"
    "ax.set_title('Risk Positioning: LLTV vs Utilization\\n(bubble size proportional to log borrow USD)',\n"
    "             fontweight='bold')\n"
    "patches = [\n"
    "    mpatches.Patch(color=C_BLUE,   label='sdeUSD'),\n"
    "    mpatches.Patch(color=C_ORANGE, label='deUSD'),\n"
    "    mpatches.Patch(color=C_GREEN,  label='xUSD'),\n"
    "]\n"
    "ax.legend(handles=patches, fontsize=9)\n"
    "ax.grid(alpha=0.25)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
))

cells.append(code(
    "# Borrower concentration in key market\n"
    "key_pos = positions.get(KEY_MARKET_UK, [])\n"
    "total_borrow = df_mkts[df_mkts['uniqueKey']==KEY_MARKET_UK]['borrow_usd'].values[0]\n"
    "rows = [{'user': p['user']['address'], 'borrow_usd': float(p['state'].get('borrowAssetsUsd') or 0)}\n"
    "        for p in key_pos if float(p['state'].get('borrowAssetsUsd') or 0) > 0]\n"
    "rows = sorted(rows, key=lambda r: r['borrow_usd'], reverse=True)\n"
    "other = max(0, total_borrow - sum(r['borrow_usd'] for r in rows))\n"
    "labels = [r['user'][:10]+'...' for r in rows]\n"
    "vals   = [r['borrow_usd'] for r in rows]\n"
    "if other > 1:\n"
    "    labels.append('Other')\n"
    "    vals.append(other)\n\n"
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))\n"
    "colors = [C_RED, C_ORANGE, C_BLUE, C_GREY]\n\n"
    "def _pct_lbl(pct):\n"
    "    return f'{pct:.1f}%' if pct >= 3 else ''\n\n"
    "wedges, _, _ = ax1.pie(\n"
    "    vals, autopct=_pct_lbl, colors=colors[:len(vals)], startangle=140, pctdistance=0.72,\n"
    "    wedgeprops=dict(edgecolor='white', linewidth=1.5),\n"
    "    textprops=dict(fontsize=9),\n"
    ")\n"
    "leg_lbls = [f'{lab}: {fmt_m(v)} ({v/total_borrow*100:.2f}%)' for lab, v in zip(labels, vals)]\n"
    "ax1.legend(wedges, leg_lbls, loc='center left', bbox_to_anchor=(1.02, 0.5), fontsize=8)\n"
    "ax1.set_title('Borrower concentration\\nsdeUSD/USDC market', fontweight='bold')\n"
    "ax2.barh([l[:18] for l in labels], vals, color=colors[:len(vals)], edgecolor='white')\n"
    "for i, v in enumerate(vals):\n"
    "    ax2.text(v*1.01, i, fmt_m(v), va='center', fontsize=9)\n"
    "ax2.set_xlabel('USD')\n"
    "ax2.set_title(f'Borrow amounts  (total: {fmt_m(total_borrow)})', fontweight='bold')\n"
    "ax2.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x,_: f'${x/1e6:.0f}M'))\n"
    "ax2.invert_yaxis()\n"
    "ax2.grid(axis='x', alpha=0.3)\n"
    "plt.suptitle('Q2 · Borrower concentration in the dominant incident market',\n"
    "             fontweight='bold', y=1.02)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "if rows:\n"
    "    print(f'Top borrower holds {rows[0][\"borrow_usd\"]/total_borrow*100:.1f}% of all borrow in this market.')\n"
))

cells.append(md(
    "### What this tells us about losses\n\n"
    "- A **single address** holds essentially 100% of the $130M borrow in sdeUSD/USDC.\n"
    "- This is a **self-funded collateral loop**: the same entity deposited sdeUSD as supply, "
    "then borrowed USDC against it. The market was never an open lending venue.\n"
    "- When sdeUSD depegged, the collateral value dropped but the oracle was slow or silent. "
    "By the time any liquidation would be possible, the pool already had **zero liquidity** — "
    "the borrower had drawn down all the supply.\n"
    "- The `bad_debt_unrealized` flag on deUSD/USDC markets means Morpho's accounting "
    "has internally recognized some positions exceed recoverable value, but the $130M sdeUSD "
    "position doesn't carry this label yet because the oracle returned null "
    "(the contract could not confirm the shortfall).\n"
))

cells.append(code(
    "# Liquidation recovery comparison\n"
    "total_out = df_mkts['borrow_usd'].sum()\n"
    "recovered = sum(\n"
    "    float(tx['data'].get('repaidAssetsUsd', 0))\n"
    "    for tx in liq_txs if tx.get('data')\n"
    ")\n\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n\n"
    "# Left: liquidation events\n"
    "if liq_txs:\n"
    "    liq_rows = []\n"
    "    for tx in liq_txs:\n"
    "        d = tx.get('data', {})\n"
    "        liq_rows.append({\n"
    "            'Date': ts(tx['timestamp']).strftime('%b %d, %H:%M'),\n"
    "            'Repaid': float(d.get('repaidAssetsUsd', 0)),\n"
    "            'Seized': float(d.get('seizedAssetsUsd', 0)),\n"
    "            'Bad debt': float(d.get('badDebtAssetsUsd', 0)),\n"
    "        })\n"
    "    df_liq = pd.DataFrame(liq_rows)\n"
    "    x = range(len(df_liq))\n"
    "    w = 0.28\n"
    "    axes[0].barh([i+w for i in x], df_liq['Repaid'],   height=w, color=C_BLUE,   label='Repaid $')\n"
    "    axes[0].barh([i   for i in x], df_liq['Seized'],   height=w, color=C_ORANGE, label='Seized $')\n"
    "    axes[0].barh([i-w for i in x], df_liq['Bad debt'], height=w, color=C_RED,    label='Bad debt $')\n"
    "    axes[0].set_yticks(list(x))\n"
    "    axes[0].set_yticklabels(df_liq['Date'], fontsize=9)\n"
    "    axes[0].invert_yaxis()\n"
    "    axes[0].legend(fontsize=8)\n"
    "    axes[0].set_title('Individual Liquidation Events\\n(Nov 2025)', fontweight='bold')\n"
    "    axes[0].grid(axis='x', alpha=0.3)\n"
    "else:\n"
    "    axes[0].text(0.5, 0.5, 'No liquidations in window', ha='center', va='center', fontsize=13)\n\n"
    "# Right: recovery rate\n"
    "categories = ['Borrow outstanding\\n(all incident markets)', 'Recovered via\\nliquidations']\n"
    "amounts    = [total_out, recovered]\n"
    "col_list   = [C_RED, C_GREEN]\n"
    "axes[1].barh(categories, amounts, color=col_list, edgecolor='white')\n"
    "for i, v in enumerate(amounts):\n"
    "    axes[1].text(v + max(amounts)*0.01, i, fmt_m(v), va='center', fontsize=10, fontweight='bold')\n"
    "axes[1].set_xlabel('USD')\n"
    "axes[1].set_title('Recovery Rate vs Outstanding Borrow', fontweight='bold')\n"
    "axes[1].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x,_: f'${x/1e6:.0f}M'))\n"
    "axes[1].grid(axis='x', alpha=0.3)\n"
    "plt.suptitle('Q2 · Loss accounting: what was recovered?', fontweight='bold', y=1.01)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "pct = recovered/total_out*100 if total_out else 0\n"
    "print(f'Total borrow outstanding:   {fmt_m(total_out)}')\n"
    "print(f'Recovered via liquidations: {fmt_m(recovered)}  ({pct:.4f}%)')\n"
    "print('Effective recovery rate: essentially zero.')\n"
))

cells.append(md(
    "### Summary: Q1-2 answers\n\n"
    "| | Answer |\n"
    "|---|---|\n"
    "| **Which markets were exposed?** | 11 markets across Ethereum and Arbitrum used xUSD / deUSD / sdeUSD as collateral. "
    "One market (sdeUSD/USDC on Ethereum) accounts for >99.9% of all borrow. |\n"
    "| **Which vaults were exposed?** | **Zero** curator-managed vaults had whitelisted allocation to any incident market. "
    "All supply came directly from isolated counterparties, not from MetaMorpho vaults. |\n"
    "| **Bad debt?** | The sdeUSD/USDC market carries ~$130M outstanding borrow with collateral "
    "now worth a fraction of face value — unrealized bad debt. Only 2 liquidation transactions "
    "occurred in November, recovering less than $2 combined. |\n"
))

# ─── 3: CURATOR ACTIONS ───────────────────────────────────────────────────────
cells.append(md(
    "## 3 · Q3-4: Did curators exit early, and what actions did they take?\n\n"
    "### Research plan\n\n"
    "To answer whether curators exited before the incident, we look for:\n"
    "- **Allocation changes** — vaults reducing caps/queues to incident markets before the depeg\n"
    "- **Market activity** — borrow/repay/supply/withdraw flows in the window\n"
    "- **MetaMorpho events** — deposit/withdraw from curator-managed vaults\n\n"
    "### Key constraint\n"
    "Because **no curator-managed vault ever held whitelisted allocation to these markets**, "
    "the 'did curators exit?' question has a nuanced answer: curators who reviewed these markets "
    "and never allocated were **effectively never exposed** — an implicit risk-management success. "
    "There is no evidence of a late-stage panicked withdrawal because there was no allocation to withdraw.\n"
))

cells.append(code(
    "# Market activity flows: what transaction types occurred?\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n"
    "for ax_idx, uk in enumerate([\n"
    "    '0x0f9563442d64ab3bd3bcb27058db0b0d4046a4c46f0acd811dacae9551d2b129',\n"
    "    '0xbd1ad3b968f5f0552dbd8cf1989a62881407c5cccf9e49fb3657c8731caf0c1f',\n"
    "]):\n"
    "    ax = axes[ax_idx]\n"
    "    txs = activity.get(uk, [])\n"
    "    mkt = next((m for m in markets if m['uniqueKey']==uk), {})\n"
    "    lbl = (mkt.get('collateralAsset',{}).get('symbol','?') + '/'\n"
    "           + mkt.get('loanAsset',{}).get('symbol','?'))\n"
    "    if txs:\n"
    "        tc = Counter(t['type'] for t in txs)\n"
    "        types  = list(tc.keys())\n"
    "        counts = list(tc.values())\n"
    "        bc = [C_GREEN if 'Supply' in t else (C_RED if 'Withdraw' in t\n"
    "              else (C_ORANGE if 'Borrow' in t else C_BLUE)) for t in types]\n"
    "        bars = ax.bar(types, counts, color=bc, edgecolor='white', width=0.6)\n"
    "        for bar, cnt in zip(bars, counts):\n"
    "            ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.05,\n"
    "                    str(cnt), ha='center', fontsize=11, fontweight='bold')\n"
    "        ax.set_xticklabels(\n"
    "            [t.replace('Market','').replace('Collateral',' Coll.') for t in types],\n"
    "            rotation=30, ha='right', fontsize=9)\n"
    "    else:\n"
    "        ax.text(0.5, 0.5, 'No activity in window', ha='center', va='center', fontsize=11)\n"
    "    ax.set_title(f'{lbl}\\nActivity types (Nov 2025, capped)', fontweight='bold')\n"
    "    ax.set_ylabel('Transaction count')\n"
    "    ax.grid(axis='y', alpha=0.3)\n"
    "plt.suptitle('Q4 · What market participants were doing during the incident',\n"
    "             fontweight='bold', y=1.02)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
))

cells.append(code(
    "# Activity timeline scatter\n"
    "fig, ax = plt.subplots(figsize=(13, 5))\n"
    "type_colors = {\n"
    "    'MarketSupply':             C_GREEN,\n"
    "    'MarketWithdraw':           C_RED,\n"
    "    'MarketBorrow':             C_ORANGE,\n"
    "    'MarketRepay':              C_BLUE,\n"
    "    'MarketSupplyCollateral':   C_PURPLE,\n"
    "    'MarketWithdrawCollateral': C_GREY,\n"
    "}\n"
    "for uk, txs in activity.items():\n"
    "    for t in txs:\n"
    "        dt = ts(t['timestamp'])\n"
    "        typ = t['type']\n"
    "        ax.scatter(dt, typ.replace('Market',''), color=type_colors.get(typ, 'gray'),\n"
    "                   s=60, alpha=0.8, zorder=3)\n"
    "ax.set_title('Q4 · Market transaction timeline — all incident-collateral markets (Nov 2025)',\n"
    "             fontweight='bold')\n"
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))\n"
    "ax.xaxis.set_major_locator(mdates.DayLocator(interval=3))\n"
    "plt.setp(ax.xaxis.get_majorticklabels(), rotation=30)\n"
    "ax.grid(alpha=0.2)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "print('Each dot = 1 transaction. Multiple markets overlaid. Capped at 15 txs/market.')\n"
))

cells.append(code(
    "# Vault exposure check\n"
    "print('=== Vault allocation to incident markets ===')\n"
    "print(f'V1 vaults with matching allocation: {len(v1_incident)}')\n"
    "if not v1_incident:\n"
    "    print('  ZERO curator-managed V1 vaults held allocation to incident markets.')\n"
    "print()\n"
    "print('Supplying vaults per market (snapshot):')\n"
    "any_sv = False\n"
    "for uk, svs in supply_vaults.items():\n"
    "    mkt = next((m for m in markets if m['uniqueKey']==uk), {})\n"
    "    lbl = (mkt.get('collateralAsset',{}).get('symbol','?') + '/'\n"
    "           + mkt.get('loanAsset',{}).get('symbol','?'))\n"
    "    if svs:\n"
    "        any_sv = True\n"
    "        print(f'  [{lbl}] -> {len(svs)} vault(s): ' + ', '.join(v.get('name','?') for v in svs))\n"
    "    else:\n"
    "        print(f'  [{lbl}] -> no supplying vaults')\n"
    "if not any_sv:\n"
    "    print()\n"
    "    print('NO vault currently supplying to any incident-collateral market.')\n"
    "    print('All supply came from direct (non-vault) depositors.')\n"
))

cells.append(code(
    "# Top curator vaults by TVL — context\n"
    "top5 = sorted(v2_top, key=lambda v: v.get('totalAssetsUsd',0), reverse=True)[:5]\n"
    "df_top5 = pd.DataFrame([{\n"
    "    'Vault': v['name'][:30],\n"
    "    'TVL $M': round(v['totalAssetsUsd']/1e6, 1),\n"
    "    'Liquidity $M': round(v.get('liquidityUsd',0)/1e6, 1),\n"
    "    'Liq%': round(v.get('liquidityUsd',0)/v['totalAssetsUsd']*100, 1) if v.get('totalAssetsUsd') else 0,\n"
    "} for v in top5])\n"
    "x = range(len(df_top5))\n"
    "fig, ax = plt.subplots(figsize=(11, 4))\n"
    "ax.bar([i-0.2 for i in x], df_top5['TVL $M'],       width=0.4, color=C_BLUE,  label='TVL')\n"
    "ax.bar([i+0.2 for i in x], df_top5['Liquidity $M'], width=0.4, color=C_GREEN, label='Available Liquidity')\n"
    "ax.set_xticks(list(x))\n"
    "ax.set_xticklabels(df_top5['Vault'], rotation=25, ha='right', fontsize=9)\n"
    "ax.set_ylabel('USD Millions')\n"
    "ax.set_title('Top 5 Morpho V2 Vaults by TVL (none involved in incident)',\n"
    "             fontweight='bold')\n"
    "ax.legend(fontsize=9)\n"
    "ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x,_: f'${x:.0f}M'))\n"
    "ax.grid(axis='y', alpha=0.3)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
))

cells.append(md(
    "### Summary: Q3-4 answers\n\n"
    "| | Answer |\n"
    "|---|---|\n"
    "| **Did curators exit early?** | There were no curators to exit. The incident markets never had "
    "whitelisted vault allocation. Curators implicitly avoided these markets by never listing them. |\n"
    "| **What did curators do in response?** | Because no curator vault was exposed, there were no "
    "curator emergency actions visible in the data. The markets functioned entirely outside the "
    "curator-managed ecosystem. |\n"
    "| **Who *was* active?** | Direct market participants — likely the same entity operating the "
    "collateral loop — performed supply, withdraw, and collateral management operations. |\n"
    "| **The broader lesson** | The curator layer successfully filtered out these markets. "
    "The incident was contained to a self-funded bilateral structure outside the primary vault system. |\n"
))

# ─── 4: LIQUIDITY ─────────────────────────────────────────────────────────────
cells.append(md(
    "## 4 · Q5: How did vault liquidity evolve? Which vaults were more impacted?\n\n"
    "### Research plan\n\n"
    "We have 30-day daily timeseries for:\n"
    "- **Collateral oracle prices** — to show depeg magnitude and timing\n"
    "- **Market liquidity, borrow, and supply** — to show when/how the sdeUSD market locked\n"
    "- **Utilization** — to show the lockup trajectory\n"
    "- **Vault TVL and share price** — to show if curator-managed vaults experienced outflows\n"
))

cells.append(code(
    "# Collateral price depeg\n"
    "ASSET_COLORS = {'xUSD': C_RED, 'deUSD': C_ORANGE, 'sdeUSD': C_PURPLE}\n"
    "fig, ax = plt.subplots(figsize=(13, 5))\n"
    "for series in prices:\n"
    "    sym = series['symbol']\n"
    "    df_p = xy_to_df(series.get('historicalPriceUsd', []), 'price')\n"
    "    if df_p.empty: continue\n"
    "    color = ASSET_COLORS.get(sym, C_GREY)\n"
    "    ax.plot(df_p['date'], df_p['price'], marker='o', markersize=4,\n"
    "            linewidth=2, color=color, label=sym, zorder=3)\n"
    "    last = df_p.dropna(subset=['price']).iloc[-1]\n"
    "    ax.annotate(f\"{sym}: ${last['price']:.3f}\",\n"
    "                (last['date'], last['price']),\n"
    "                xytext=(8, 0), textcoords='offset points',\n"
    "                fontsize=8.5, color=color, fontweight='bold')\n"
    "ax.axhline(1.0, color='gray', linestyle='--', linewidth=1, label='$1.00 peg')\n"
    "ax.set_ylabel('Price (USD)')\n"
    "ax.set_title('Collateral Asset Price — Depeg during November 2025\\n'\n"
    "             '(Morpho oracle/feed data; null gaps = stale oracle)', fontweight='bold')\n"
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))\n"
    "ax.xaxis.set_major_locator(mdates.DayLocator(interval=3))\n"
    "plt.setp(ax.xaxis.get_majorticklabels(), rotation=30)\n"
    "ax.legend(fontsize=9)\n"
    "ax.set_ylim(bottom=0)\n"
    "ax.grid(alpha=0.25)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "print('xUSD fell ~94-95% from $1. sdeUSD/deUSD data is very sparse - oracle staleness.')\n"
))

cells.append(code(
    "# Dominant market: borrow / supply / liquidity + utilization\n"
    "KEY_MKT = next(m for m in hist_mkts if m['uniqueKey']==KEY_MARKET_UK)\n"
    "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(13, 8), sharex=True)\n\n"
    "for field, name, color in [\n"
    "    ('borrowAssetsUsd',    'Borrow',    C_RED),\n"
    "    ('supplyAssetsUsd',    'Supply',    C_BLUE),\n"
    "    ('liquidityAssetsUsd', 'Liquidity', C_GREEN),\n"
    "]:\n"
    "    df_f = xy_to_df(KEY_MKT['historicalState'][field], name)\n"
    "    if df_f.empty: continue\n"
    "    ax1.plot(df_f['date'], df_f[name]/1e6, label=name,\n"
    "             color=color, linewidth=2.2, marker='o', markersize=3)\n\n"
    "ax1.set_ylabel('USD Millions')\n"
    "ax1.set_title('sdeUSD/USDC — Borrow, Supply & Liquidity (Nov 2025)',\n"
    "              fontweight='bold')\n"
    "ax1.legend(fontsize=10)\n"
    "ax1.grid(alpha=0.25)\n"
    "ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x,_: f'${x:.0f}M'))\n\n"
    "df_u = xy_to_df(KEY_MKT['historicalState']['utilization'], 'util')\n"
    "ax2.fill_between(df_u['date'], df_u['util']*100, color=C_RED, alpha=0.3)\n"
    "ax2.plot(df_u['date'], df_u['util']*100, color=C_RED, linewidth=2)\n"
    "ax2.axhline(100, color='darkred', linestyle='--', linewidth=1, label='100% (locked)')\n"
    "ax2.set_ylabel('Utilization (%)')\n"
    "ax2.set_title('Utilization Rate', fontweight='bold')\n"
    "ax2.set_ylim(0, 108)\n"
    "ax2.legend(fontsize=9)\n"
    "ax2.grid(alpha=0.25)\n"
    "ax2.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))\n"
    "ax2.xaxis.set_major_locator(mdates.DayLocator(interval=3))\n"
    "plt.setp(ax2.xaxis.get_majorticklabels(), rotation=30)\n"
    "plt.suptitle('Q5 · sdeUSD/USDC market — liquidity dynamics November 2025',\n"
    "             fontweight='bold', y=1.01)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
))

cells.append(md(
    "### Reading the market dynamics\n\n"
    "1. **Borrow and supply move in lockstep** — because the same actor deposited the supply "
    "and borrowed against it, both lines are nearly identical. There was never 'free' liquidity.\n"
    "2. **Liquidity = $0 throughout** — the market was structurally illiquid from before November. "
    "The depeg didn't *create* the lock; it revealed that the lock made the position unresolvable.\n"
    "3. **Utilization ~100% from day one** — this is the fingerprint of a "
    "**self-funded collateral loop**, not a genuine lending market.\n\n"
    "> The gradual rise in borrow/supply values over the month (despite 100% utilization) "
    "reflects interest accrual compounding on the outstanding position — the debt is growing "
    "automatically even with no new activity.\n"
))

cells.append(code(
    "# All markets borrow vs liquidity\n"
    "n = len(hist_mkts)\n"
    "fig, axes = plt.subplots(n, 1, figsize=(13, 2.5*n), sharex=True)\n"
    "if n == 1: axes = [axes]\n"
    "for ax, m in zip(axes, hist_mkts):\n"
    "    lbl = f\"{m['collateralAsset']['symbol']}/{m['loanAsset']['symbol']}\"\n"
    "    df_b = xy_to_df(m['historicalState']['borrowAssetsUsd'],    'borrow')\n"
    "    df_l = xy_to_df(m['historicalState']['liquidityAssetsUsd'], 'liquidity')\n"
    "    if not df_b.empty:\n"
    "        ax.fill_between(df_b['date'], df_b['borrow'],    color=C_RED,   alpha=0.22)\n"
    "        ax.plot(df_b['date'],         df_b['borrow'],    color=C_RED,   linewidth=1.5, label='Borrow')\n"
    "    if not df_l.empty:\n"
    "        ax.fill_between(df_l['date'], df_l['liquidity'], color=C_GREEN, alpha=0.35)\n"
    "        ax.plot(df_l['date'],         df_l['liquidity'], color=C_GREEN, linewidth=1.5, label='Liquidity')\n"
    "    ax.set_ylabel('USD', fontsize=8)\n"
    "    ax.set_title(lbl, fontsize=9, fontweight='bold', pad=3)\n"
    "    ax.legend(fontsize=7, loc='upper right')\n"
    "    ax.grid(alpha=0.2)\n"
    "    ax.yaxis.set_major_formatter(mticker.FuncFormatter(\n"
    "        lambda x,_: f'${x/1e6:.0f}M' if x>=1e6 else (f'${x/1e3:.0f}k' if x>=1000 else f'${x:.0f}')))\n"
    "axes[-1].xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))\n"
    "axes[-1].xaxis.set_major_locator(mdates.DayLocator(interval=5))\n"
    "plt.setp(axes[-1].xaxis.get_majorticklabels(), rotation=30)\n"
    "plt.suptitle('Q5 · Borrow vs Liquidity across all incident-collateral markets',\n"
    "             fontweight='bold', y=1.01)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
))

cells.append(code(
    "# Vault TVL and share price\n"
    "if hist_vaults:\n"
    "    n = len(hist_vaults)\n"
    "    fig, axes = plt.subplots(n, 2, figsize=(14, 4*n), squeeze=False)\n"
    "    for i, v in enumerate(hist_vaults):\n"
    "        kind = v.get('vaultKind','?')\n"
    "        name = v.get('name', v.get('address','?'))[:40]\n"
    "        sp_field = 'sharePriceUsd' if kind=='v1' else 'sharePrice'\n"
    "        df_tvl = xy_to_df(v.get('historicalState',{}).get('totalAssetsUsd',[]), 'tvl')\n"
    "        df_sp  = xy_to_df(v.get('historicalState',{}).get(sp_field,[]),         'sp')\n"
    "        ax0, ax1 = axes[i]\n"
    "        if not df_tvl.empty:\n"
    "            ax0.plot(df_tvl['date'], df_tvl['tvl']/1e6, color=C_BLUE,\n"
    "                     linewidth=2, marker='o', markersize=3)\n"
    "            ax0.set_ylabel('$M')\n"
    "        ax0.set_title(f'[{kind.upper()}] {name} — TVL', fontsize=9, fontweight='bold')\n"
    "        ax0.grid(alpha=0.25)\n"
    "        if not df_sp.empty:\n"
    "            ax1.plot(df_sp['date'], df_sp['sp'], color=C_GREEN,\n"
    "                     linewidth=2, marker='o', markersize=3)\n"
    "        ax1.set_title('Share price', fontsize=9, fontweight='bold')\n"
    "        ax1.grid(alpha=0.25)\n"
    "        for ax in [ax0, ax1]:\n"
    "            ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))\n"
    "            ax.xaxis.set_major_locator(mdates.DayLocator(interval=5))\n"
    "            plt.setp(ax.xaxis.get_majorticklabels(), rotation=30, fontsize=8)\n"
    "    plt.suptitle('Q5 · Vault TVL & share price — November 2025',\n"
    "                 fontweight='bold', y=1.01)\n"
    "    plt.tight_layout()\n"
    "    plt.show()\n"
    "else:\n"
    "    print('No historical vault data (all incident markets had zero vault allocation).')\n"
))

cells.append(md(
    "### Summary: Q5 answer\n\n"
    "| | Answer |\n"
    "|---|---|\n"
    "| **Which vaults were most impacted?** | No curator-managed vault was directly impacted. |\n"
    "| **How did liquidity evolve?** | The sdeUSD/USDC market was at 0% liquidity and 100% "
    "utilization **from the start of November** — the depeg didn't cause the illiquidity, it made "
    "the existing illiquidity catastrophic by eliminating collateral value simultaneously. |\n"
    "| **Which markets were more impacted?** | sdeUSD/USDC ($130M borrow) is the only "
    "material market. All others are sub-$25k. |\n"
))

# ─── 5: DEBRIEF — LIQUIDATIONS ────────────────────────────────────────────────
cells.append(md(
    "## 5 · Debrief: Why didn't the liquidation mechanism work?\n\n"
    "> *'Why didn't liquidations happen, or why did they take so long?'*\n\n"
    "### Hypothesis framework\n\n"
    "There are three classical failure modes for on-chain liquidation:\n\n"
    "| Failure mode | Description |\n"
    "|---|---|\n"
    "| **Oracle failure** | Oracle doesn't mark positions as unhealthy — liquidation threshold never crossed |\n"
    "| **Economic unviability** | Liquidating is technically possible but unprofitable — no bot acts |\n"
    "| **Pool illiquidity** | Liquidator cannot source the repayment asset from the pool |\n\n"
    "In the sdeUSD/USDC market, **all three operated simultaneously**.\n"
))

cells.append(code(
    "# Market state anatomy\n"
    "KEY_DATA = next(m for m in markets if m['uniqueKey']==KEY_MARKET_UK)\n"
    "lltv     = float(KEY_DATA['lltv']) / 1e18\n"
    "borrow   = float(KEY_DATA['state']['borrowAssetsUsd'] or 0)\n"
    "supply   = float(KEY_DATA['state']['supplyAssetsUsd'] or 0)\n"
    "liq_amt  = float(KEY_DATA['state']['liquidityAssetsUsd'] or 0)\n"
    "util     = float(KEY_DATA['state']['utilization'] or 0)\n"
    "coll_usd = KEY_DATA['state']['collateralAssetsUsd']\n\n"
    "fig, axes = plt.subplots(1, 3, figsize=(14, 5))\n\n"
    "# Capital structure\n"
    "axes[0].bar(['Borrow', 'Supply', 'Liquidity'], [borrow, supply, liq_amt],\n"
    "            color=[C_RED, C_BLUE, C_GREEN], edgecolor='white', width=0.55)\n"
    "for i, v in enumerate([borrow, supply, liq_amt]):\n"
    "    axes[0].text(i, v*1.03, fmt_m(v), ha='center', fontsize=9.5, fontweight='bold')\n"
    "axes[0].set_title('Capital structure\\nsdeUSD/USDC snapshot', fontweight='bold')\n"
    "axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x,_: f'${x/1e6:.0f}M'))\n"
    "axes[0].grid(axis='y', alpha=0.25)\n\n"
    "# Utilization gauge\n"
    "theta = np.linspace(np.pi, 0, 300)\n"
    "axes[1].plot(np.cos(theta), np.sin(theta), color='#ddd', linewidth=20, solid_capstyle='round')\n"
    "fill = np.linspace(np.pi, np.pi - util*np.pi, 300)\n"
    "axes[1].plot(np.cos(fill), np.sin(fill), color=C_RED, linewidth=20, solid_capstyle='round')\n"
    "axes[1].text(0, -0.05, f'{util*100:.0f}%', ha='center', va='center',\n"
    "             fontsize=30, fontweight='bold', color=C_RED)\n"
    "axes[1].text(0, -0.45, 'Pool utilization', ha='center', fontsize=11)\n"
    "axes[1].set_xlim(-1.3,1.3); axes[1].set_ylim(-0.7,1.2)\n"
    "axes[1].axis('off')\n"
    "axes[1].set_title('Pool utilization', fontweight='bold')\n\n"
    "# Barriers\n"
    "barriers = ['Oracle returned null\\n(no unhealthy signal)',\n"
    "            '$0 pool liquidity\\n(can\\'t repay from pool)',\n"
    "            'Collateral ~$0\\n(no liquidation profit)',\n"
    "            'Single $130M borrower\\n(no easy partial liq.)']\n"
    "hbars = axes[2].barh(barriers, [10,10,9,8], color=C_RED, alpha=0.75, edgecolor='white')\n"
    "axes[2].set_xlim(0,12)\n"
    "axes[2].set_xticks([])\n"
    "axes[2].set_title('Liquidation barriers\\n(all present simultaneously)', fontweight='bold')\n"
    "for bar, s in zip(hbars, [10,10,9,8]):\n"
    "    axes[2].text(s+0.1, bar.get_y()+bar.get_height()/2,\n"
    "                 'BLOCKED' if s==10 else 'SEVERE', va='center', fontsize=8, color=C_RED)\n"
    "axes[2].invert_yaxis()\n"
    "axes[2].grid(axis='x', alpha=0.2)\n"
    "plt.suptitle('Why liquidation failed: structural anatomy', fontweight='bold', y=1.02)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "print(f'Oracle-priced collateral USD: {coll_usd}  (null = no pricing from oracle)')\n"
))

cells.append(code(
    "# Depeg timeline vs liquidation activity\n"
    "fig, ax1 = plt.subplots(figsize=(13, 5))\n\n"
    "for series, color, sym in [(next((s for s in prices if s['symbol']=='xUSD'), None), C_RED, 'xUSD'),\n"
    "                            (next((s for s in prices if s['symbol']=='sdeUSD'), None), C_PURPLE, 'sdeUSD')]:\n"
    "    if series is None: continue\n"
    "    df_p = xy_to_df(series['historicalPriceUsd'], 'price')\n"
    "    if df_p.empty: continue\n"
    "    ax1.plot(df_p['date'], df_p['price'], color=color, linewidth=2.2,\n"
    "             label=f'{sym} price', alpha=0.85)\n"
    "    # shade depeg region\n"
    "    ax1.fill_between(df_p['date'], df_p['price'], 1.0,\n"
    "                     where=(df_p['price'] < 1.0), alpha=0.1, color=color)\n\n"
    "ax1.axhline(1.0, color='gray', linestyle='--', linewidth=0.9, label='$1.00 peg')\n"
    "ax1.set_ylabel('Asset price (USD)')\n"
    "ax1.set_ylim(bottom=0)\n"
    "ax1.legend(loc='upper right', fontsize=9)\n\n"
    "ax2 = ax1.twinx()\n"
    "liq_by_day = liq_summary.get('liquidationsPerDayUtc', {})\n"
    "if liq_by_day:\n"
    "    liq_dates  = [pd.Timestamp(d) for d in liq_by_day]\n"
    "    liq_counts = list(liq_by_day.values())\n"
    "    ax2.bar(liq_dates, liq_counts, color=C_ORANGE, alpha=0.8, width=0.7,\n"
    "            label='Liquidation txs')\n"
    "    ax2.set_ylabel('Liquidation count', color=C_ORANGE)\n"
    "    ax2.tick_params(axis='y', labelcolor=C_ORANGE)\n"
    "    ax2.legend(loc='upper left', fontsize=9)\n"
    "    ax2.set_ylim(0, max(liq_counts)*5)\n\n"
    "ax1.set_title('Depeg timeline vs liquidation activity\\n'\n"
    "              '(null price gaps = oracle staleness / silence during stress)',\n"
    "              fontweight='bold')\n"
    "ax1.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))\n"
    "ax1.xaxis.set_major_locator(mdates.DayLocator(interval=2))\n"
    "plt.setp(ax1.xaxis.get_majorticklabels(), rotation=30)\n"
    "ax1.grid(alpha=0.2)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
))

cells.append(md(
    "### Root causes: structured evidence\n\n"
    "#### 1. Oracle failure (primary mechanism)\n"
    "The Morpho oracle for sdeUSD/USDC returned **`null`** for `collateralAssetsUsd`. "
    "During the depeg, if the price feed staled or returned below minimum, Morpho's contract "
    "received either a stale (high) price or zero. A stale price means the contract never sees "
    "the position as undercollateralized — the liquidation threshold is never crossed. "
    "This is corroborated by the **sparse/null oracle data** in our timeseries.\n\n"
    "#### 2. Zero pool liquidity (structural lock)\n"
    "`liquidityAssetsUsd = $0` throughout at 100% utilization. A liquidator must "
    "**source $130M USDC externally** — via flash loan or held capital — to repay the borrow. "
    "Combined with receiving near-worthless sdeUSD as seized collateral, no bot has a "
    "profitable trade structure.\n\n"
    "#### 3. Collateral worth ~$0 (no economic incentive)\n"
    "Even with a flash loan, the math fails: seizing sdeUSD at a 5-10% liquidation bonus "
    "on a token worth $0.01 yields approximately $0 profit — insufficient to cover gas, "
    "flash loan fees, or DEX slippage on unwinding the position.\n\n"
    "#### 4. Single borrower concentration\n"
    "The entire $130M borrow is one address. Partial liquidations are possible in Morpho, "
    "but a partial liquidation only helps if it restores health. With collateral at ~$0, "
    "no partial amount returns the borrower to solvency. There is no incremental path forward.\n\n"
    "> **The key insight for integrators:** Morpho's liquidation mechanism is economically "
    "rational — it works when there is a profit to be made. This incident removed *all* "
    "profit from liquidation simultaneously. The failure was not a bug; it was the predictable "
    "outcome of oracle failure + illiquidity + zero collateral value occurring together.\n"
))

# ─── 6: SHARED LIQUIDITY ──────────────────────────────────────────────────────
cells.append(md(
    "## 6 · Debrief: Is liquidity risk shared across Morpho markets?\n\n"
    "> *'While Morpho markets are isolated, some claim liquidity risks are still shared. "
    "What do you think?'*\n\n"
    "### The tension\n"
    "Morpho guarantees **accounting isolation** — bad debt in one market cannot directly "
    "flow to another. But *liquidity risk* — the risk of being unable to redeem when you want "
    "to — is a different question with a more nuanced answer.\n"
))

cells.append(code(
    "# Architecture visualization: isolation vs shared risk channels\n"
    "fig, ax = plt.subplots(figsize=(13, 6))\n"
    "ax.set_xlim(0, 13); ax.set_ylim(0, 8)\n"
    "ax.axis('off')\n\n"
    "def box(ax, x, y, w, h, title, body, fc, ec):\n"
    "    rect = mpatches.FancyBboxPatch((x,y), w, h, boxstyle='round,pad=0.08',\n"
    "                                    fc=fc, ec=ec, linewidth=2, zorder=2)\n"
    "    ax.add_patch(rect)\n"
    "    ax.text(x+w/2, y+h-0.3, title, ha='center', va='top',\n"
    "            fontsize=9, fontweight='bold', color='white', zorder=3)\n"
    "    ax.text(x+w/2, y+h/2-0.15, body, ha='center', va='center',\n"
    "            fontsize=7.5, color='white', zorder=3, linespacing=1.6)\n\n"
    "box(ax, 0.3, 3.5, 3.2, 3.8,\n"
    "    'sdeUSD/USDC\\n(Incident Market)',\n"
    "    'Borrow: $130M\\nLiquidity: $0\\nUtil: 100%\\nNo vault allocation',\n"
    "    '#8B0000', '#5A0000')\n"
    "box(ax, 4.5, 3.5, 3.2, 3.8,\n"
    "    'WETH/USDC\\n(Healthy Market)',\n"
    "    'Borrow: $400M+\\nLiquidity: $50M+\\nUtil: ~80%\\nMultiple vault alloc.',\n"
    "    '#1A5276', '#154360')\n"
    "box(ax, 8.8, 3.5, 3.8, 3.8,\n"
    "    'MetaMorpho Vault\\n(Curator-managed)',\n"
    "    'Allocates across\\nmultiple markets\\n\\nDepositors hold\\n1 share token',\n"
    "    '#1E8449', '#145A32')\n\n"
    "# Accounting isolation\n"
    "ax.annotate('', xy=(3.5, 5.5), xytext=(4.5, 5.5),\n"
    "            arrowprops=dict(arrowstyle='<->', color=C_RED, lw=2.5))\n"
    "ax.text(4.0, 5.95, 'Accounting\\nisolated', ha='center', fontsize=8,\n"
    "        color=C_RED, fontweight='bold')\n\n"
    "# Shared via vault outflows\n"
    "ax.annotate('', xy=(8.8, 5.3), xytext=(7.7, 5.3),\n"
    "            arrowprops=dict(arrowstyle='->', color=C_ORANGE, lw=2.5))\n"
    "ax.text(8.25, 5.7, 'Shared via\\nvault withdrawal', ha='center',\n"
    "        fontsize=8, color=C_ORANGE, fontweight='bold')\n\n"
    "# Depositor redemption cascade\n"
    "ax.annotate('', xy=(6.1, 3.5), xytext=(6.1, 2.3),\n"
    "            arrowprops=dict(arrowstyle='->', color=C_GREY, lw=1.8))\n"
    "ax.text(6.1, 2.0, 'Redemption wave -> vault pulls from ALL allocated markets',\n"
    "        ha='center', fontsize=8, color=C_GREY)\n\n"
    "ax.text(6.5, 7.75, 'Architecture: Accounting Isolation vs Shared Liquidity Risk',\n"
    "        ha='center', fontsize=11, fontweight='bold')\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
))

cells.append(code(
    "# Liquidity comparison: incident vs healthy markets\n"
    "top5 = sorted(v2_top, key=lambda v: v.get('totalAssetsUsd',0), reverse=True)[:5]\n"
    "all_names = ['sdeUSD/USDC\\n(incident)', 'deUSD/USDC\\n(incident)'] + [v['name'][:20] for v in top5]\n"
    "all_tvls  = [borrow, 20585] + [v.get('totalAssetsUsd',0) for v in top5]\n"
    "all_liqs  = [0, 0] + [v.get('liquidityUsd',0) for v in top5]\n"
    "all_cols  = [C_RED, C_ORANGE] + [C_BLUE]*5\n\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n"
    "axes[0].bar(all_names, [v/1e6 for v in all_tvls], color=all_cols, edgecolor='white', width=0.6)\n"
    "axes[0].set_ylabel('USD Millions')\n"
    "axes[0].set_title('Borrow/TVL Scale Comparison\\nIncident Markets vs Active Vaults', fontweight='bold')\n"
    "axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x,_: f'${x:.0f}M'))\n"
    "axes[0].set_xticklabels(all_names, rotation=30, ha='right', fontsize=8)\n"
    "axes[0].grid(axis='y', alpha=0.3)\n\n"
    "all_liq_pct = [0, 0] + [\n"
    "    v.get('liquidityUsd',0)/v.get('totalAssetsUsd',1)*100 for v in top5]\n"
    "axes[1].bar(all_names, all_liq_pct, color=all_cols, edgecolor='white', width=0.6)\n"
    "for i, p in enumerate(all_liq_pct):\n"
    "    axes[1].text(i, p+0.5, f'{p:.0f}%', ha='center', fontsize=9)\n"
    "axes[1].axhline(20, color='gray', linestyle='--', linewidth=0.9, label='20% guideline')\n"
    "axes[1].set_ylabel('Liquidity / TVL (%)')\n"
    "axes[1].set_title('Available Liquidity Rate\\nIncident vs Active Markets', fontweight='bold')\n"
    "axes[1].set_xticklabels(all_names, rotation=30, ha='right', fontsize=8)\n"
    "axes[1].legend(fontsize=8)\n"
    "axes[1].grid(axis='y', alpha=0.3)\n"
    "plt.suptitle('6 · Liquidity: incident context vs active protocol', fontweight='bold', y=1.01)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
))

cells.append(md(
    "### The verdict: isolation is real but incomplete\n\n"
    "**What isolation protects:**\n"
    "- The $130M bad debt in sdeUSD/USDC **cannot** automatically reduce the share price "
    "of a WETH/USDC vault depositor. Accounting is fully siloed.\n"
    "- Liquidation shortfalls in one market do not trigger margin calls elsewhere.\n\n"
    "**What isolation does NOT protect against:**\n\n"
    "| Risk channel | Mechanism | Isolated? |\n"
    "|---|---|---|\n"
    "| Accounting contagion | Bad debt in market A -> losses in market B | Yes - fully isolated |\n"
    "| Vault withdrawal cascade | Panic withdrawal -> vault liquidates across ALL allocated markets | No - shared |\n"
    "| Oracle/confidence risk | Major Morpho incident -> broad depositor fear | No - shared |\n"
    "| Reputational risk | '$130M Morpho bad debt' headline -> withdrawals across all vaults | No - shared |\n\n"
    "**This incident specifically:**\n"
    "Because no curator vault allocated to incident markets, the vault-level contagion "
    "channel was not activated. This is the best-case isolation scenario. But the $130M "
    "bad debt was **completely opaque** to the curator-managed ecosystem — no curator's "
    "allocation dashboard showed this risk, which is itself a monitoring gap.\n\n"
    "**The key insight for integrators:**\n"
    "When a curator vault *does* allocate across markets that include stressed assets, "
    "depositors face shared liquidity risk even though markets are isolated. "
    "A single large redemption wave can drain liquidity from multiple healthy markets "
    "simultaneously. Morpho's isolation is an **accounting guarantee**, not a "
    "**liquidity guarantee**. Plan monitoring and liquidity buffers accordingly.\n"
))

nb.cells = cells

with open("/Users/gabe/Projects/morpho-risk-case-study/analysis.ipynb", "w") as f:
    nbf.write(nb, f)
print("Wrote analysis.ipynb")